language: python
python:
  - "2.7"

install: "pip install -r dev-requirements.txt"

env:
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=py32
  - TOXENV=py33
  - TOXENV=pep8

script:
  - tox

notifications:
  webhooks:
    secure: "bhp+RSiGK0JmMtXjxxXwYCZRdEXuyIBVUcbokHnEtbjO1zdmXw49KdiqnCrDU29/g9l/RMESsBybVB1CpISPsoKVDoXeULyx84F7IZ2OkmF0qkSH8ju+rrKCaMYxDik+7hoNeVX8tloDkaXm1GhN2FIcesshv5mVr0oQpUiPcU8="
